[env]
TERM = "alacritty-direct"

[window.padding]
x = 3
y = 3

[window]
decorations = "None"
dynamic_title = false

[font]
# size = 7.2
size = 8.2
offset = { x = 1, y = 1 }

[font.normal]
# family = "CaskaydiaCoveNerdFont"
family = "CozetteVector"

[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
